version: '3'
networks:
  wpbot:
    driver: bridge
volumes:
  mysql: {}
  wordpress: {}
services:
  database:
    image: mariadb:latest
    volumes:
      - ./.docker/config/db:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wpbot
      MYSQL_PASSWORD: wpbot
      MYSQL_DATABASE: wpbot
    restart: on-failure
    networks:
      - wpbot
  wordpress:
    image: wordpress:5.2.3-php7.3-fpm-alpine
    depends_on:
      - database
    working_dir: /var/www/html
    volumes:
      - wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wpbot-commands
      - ./.docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wpbot
      WORDPRESS_DB_PASSWORD: wpbot
      WORDPRESS_DB_NAME: wpbot
      WORDPRESS_VERSION: latest
      WORDPRESS_DEBUG: 1
    networks:
      - wpbot
  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wpbot-commands
      - ./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/config/certs:/etc/nginx/certs
    restart: on-failure
    networks:
      wpbot:
        aliases:
          - wpbot.localhost
